/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ThankYouRouteImport } from './routes/thank-you'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as ShopRouteImport } from './routes/shop'
import { Route as ServicesRouteImport } from './routes/services'
import { Route as ProgramsRouteImport } from './routes/programs'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as PortfolioRouteImport } from './routes/portfolio'
import { Route as LoginRouteImport } from './routes/login'
import { Route as FreeClassRouteImport } from './routes/free-class'
import { Route as EventsRouteImport } from './routes/events'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as BookRouteImport } from './routes/book'
import { Route as BlogRouteImport } from './routes/blog'
import { Route as AboutRouteImport } from './routes/about'
import { Route as StudentRouteImport } from './routes/_student'
import { Route as ClientRouteImport } from './routes/_client'
import { Route as AdminRouteImport } from './routes/_admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CoursesIndexRouteImport } from './routes/courses.index'
import { Route as CoursesSlugRouteImport } from './routes/courses.$slug'
import { Route as AdminSignupRouteImport } from './routes/admin.signup'
import { Route as AdminLoginRouteImport } from './routes/admin.login'
import { Route as StudentStudentRouteImport } from './routes/_student/student'
import { Route as ClientClientRouteImport } from './routes/_client/client'
import { Route as AdminAdminRouteImport } from './routes/_admin/admin'
import { Route as AdminAdminIndexRouteImport } from './routes/_admin/admin.index'
import { Route as CoursesSlugCheckoutRouteImport } from './routes/courses_.$slug.checkout'
import { Route as StudentStudentResourcesRouteImport } from './routes/_student/student.resources'
import { Route as StudentStudentProgressRouteImport } from './routes/_student/student.progress'
import { Route as StudentStudentProfileRouteImport } from './routes/_student/student.profile'
import { Route as StudentStudentCoursesRouteImport } from './routes/_student/student.courses'
import { Route as StudentStudentCommunityRouteImport } from './routes/_student/student.community'
import { Route as ClientClientProjectsRouteImport } from './routes/_client/client.projects'
import { Route as ClientClientProfileRouteImport } from './routes/_client/client.profile'
import { Route as ClientClientPaymentsRouteImport } from './routes/_client/client.payments'
import { Route as ClientClientMessagesRouteImport } from './routes/_client/client.messages'
import { Route as ClientClientMeetingsRouteImport } from './routes/_client/client.meetings'
import { Route as AdminAdminStudentsRouteImport } from './routes/_admin/admin.students'
import { Route as AdminAdminSettingsRouteImport } from './routes/_admin/admin.settings'
import { Route as AdminAdminPaymentsRouteImport } from './routes/_admin/admin.payments'
import { Route as AdminAdminMeetingsRouteImport } from './routes/_admin/admin.meetings'
import { Route as AdminAdminLeadsRouteImport } from './routes/_admin/admin.leads'
import { Route as AdminAdminCoursesRouteImport } from './routes/_admin/admin.courses'
import { Route as AdminAdminCommunityRouteImport } from './routes/_admin/admin.community'
import { Route as AdminAdminCmsRouteImport } from './routes/_admin/admin.cms'
import { Route as AdminAdminClientsRouteImport } from './routes/_admin/admin.clients'
import { Route as AdminAdminBookingsRouteImport } from './routes/_admin/admin.bookings'
import { Route as StudentStudentCoursesSlugRouteImport } from './routes/_student/student.courses.$slug'
import { Route as AdminAdminCoursesCourseIdRouteImport } from './routes/_admin/admin.courses.$courseId'
import { Route as StudentStudentCoursesSlugLessonIdRouteImport } from './routes/_student/student.courses.$slug.$lessonId'

const ThankYouRoute = ThankYouRouteImport.update({
  id: '/thank-you',
  path: '/thank-you',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const ShopRoute = ShopRouteImport.update({
  id: '/shop',
  path: '/shop',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesRoute = ServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => rootRouteImport,
} as any)
const ProgramsRoute = ProgramsRouteImport.update({
  id: '/programs',
  path: '/programs',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const PortfolioRoute = PortfolioRouteImport.update({
  id: '/portfolio',
  path: '/portfolio',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const FreeClassRoute = FreeClassRouteImport.update({
  id: '/free-class',
  path: '/free-class',
  getParentRoute: () => rootRouteImport,
} as any)
const EventsRoute = EventsRouteImport.update({
  id: '/events',
  path: '/events',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const BookRoute = BookRouteImport.update({
  id: '/book',
  path: '/book',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogRoute = BlogRouteImport.update({
  id: '/blog',
  path: '/blog',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const StudentRoute = StudentRouteImport.update({
  id: '/_student',
  getParentRoute: () => rootRouteImport,
} as any)
const ClientRoute = ClientRouteImport.update({
  id: '/_client',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/_admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CoursesIndexRoute = CoursesIndexRouteImport.update({
  id: '/courses/',
  path: '/courses/',
  getParentRoute: () => rootRouteImport,
} as any)
const CoursesSlugRoute = CoursesSlugRouteImport.update({
  id: '/courses/$slug',
  path: '/courses/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminSignupRoute = AdminSignupRouteImport.update({
  id: '/admin/signup',
  path: '/admin/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/admin/login',
  path: '/admin/login',
  getParentRoute: () => rootRouteImport,
} as any)
const StudentStudentRoute = StudentStudentRouteImport.update({
  id: '/student',
  path: '/student',
  getParentRoute: () => StudentRoute,
} as any)
const ClientClientRoute = ClientClientRouteImport.update({
  id: '/client',
  path: '/client',
  getParentRoute: () => ClientRoute,
} as any)
const AdminAdminRoute = AdminAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAdminIndexRoute = AdminAdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminAdminRoute,
} as any)
const CoursesSlugCheckoutRoute = CoursesSlugCheckoutRouteImport.update({
  id: '/courses_/$slug/checkout',
  path: '/courses/$slug/checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const StudentStudentResourcesRoute = StudentStudentResourcesRouteImport.update({
  id: '/resources',
  path: '/resources',
  getParentRoute: () => StudentStudentRoute,
} as any)
const StudentStudentProgressRoute = StudentStudentProgressRouteImport.update({
  id: '/progress',
  path: '/progress',
  getParentRoute: () => StudentStudentRoute,
} as any)
const StudentStudentProfileRoute = StudentStudentProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => StudentStudentRoute,
} as any)
const StudentStudentCoursesRoute = StudentStudentCoursesRouteImport.update({
  id: '/courses',
  path: '/courses',
  getParentRoute: () => StudentStudentRoute,
} as any)
const StudentStudentCommunityRoute = StudentStudentCommunityRouteImport.update({
  id: '/community',
  path: '/community',
  getParentRoute: () => StudentStudentRoute,
} as any)
const ClientClientProjectsRoute = ClientClientProjectsRouteImport.update({
  id: '/projects',
  path: '/projects',
  getParentRoute: () => ClientClientRoute,
} as any)
const ClientClientProfileRoute = ClientClientProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => ClientClientRoute,
} as any)
const ClientClientPaymentsRoute = ClientClientPaymentsRouteImport.update({
  id: '/payments',
  path: '/payments',
  getParentRoute: () => ClientClientRoute,
} as any)
const ClientClientMessagesRoute = ClientClientMessagesRouteImport.update({
  id: '/messages',
  path: '/messages',
  getParentRoute: () => ClientClientRoute,
} as any)
const ClientClientMeetingsRoute = ClientClientMeetingsRouteImport.update({
  id: '/meetings',
  path: '/meetings',
  getParentRoute: () => ClientClientRoute,
} as any)
const AdminAdminStudentsRoute = AdminAdminStudentsRouteImport.update({
  id: '/students',
  path: '/students',
  getParentRoute: () => AdminAdminRoute,
} as any)
const AdminAdminSettingsRoute = AdminAdminSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AdminAdminRoute,
} as any)
const AdminAdminPaymentsRoute = AdminAdminPaymentsRouteImport.update({
  id: '/payments',
  path: '/payments',
  getParentRoute: () => AdminAdminRoute,
} as any)
const AdminAdminMeetingsRoute = AdminAdminMeetingsRouteImport.update({
  id: '/meetings',
  path: '/meetings',
  getParentRoute: () => AdminAdminRoute,
} as any)
const AdminAdminLeadsRoute = AdminAdminLeadsRouteImport.update({
  id: '/leads',
  path: '/leads',
  getParentRoute: () => AdminAdminRoute,
} as any)
const AdminAdminCoursesRoute = AdminAdminCoursesRouteImport.update({
  id: '/courses',
  path: '/courses',
  getParentRoute: () => AdminAdminRoute,
} as any)
const AdminAdminCommunityRoute = AdminAdminCommunityRouteImport.update({
  id: '/community',
  path: '/community',
  getParentRoute: () => AdminAdminRoute,
} as any)
const AdminAdminCmsRoute = AdminAdminCmsRouteImport.update({
  id: '/cms',
  path: '/cms',
  getParentRoute: () => AdminAdminRoute,
} as any)
const AdminAdminClientsRoute = AdminAdminClientsRouteImport.update({
  id: '/clients',
  path: '/clients',
  getParentRoute: () => AdminAdminRoute,
} as any)
const AdminAdminBookingsRoute = AdminAdminBookingsRouteImport.update({
  id: '/bookings',
  path: '/bookings',
  getParentRoute: () => AdminAdminRoute,
} as any)
const StudentStudentCoursesSlugRoute =
  StudentStudentCoursesSlugRouteImport.update({
    id: '/$slug',
    path: '/$slug',
    getParentRoute: () => StudentStudentCoursesRoute,
  } as any)
const AdminAdminCoursesCourseIdRoute =
  AdminAdminCoursesCourseIdRouteImport.update({
    id: '/$courseId',
    path: '/$courseId',
    getParentRoute: () => AdminAdminCoursesRoute,
  } as any)
const StudentStudentCoursesSlugLessonIdRoute =
  StudentStudentCoursesSlugLessonIdRouteImport.update({
    id: '/$lessonId',
    path: '/$lessonId',
    getParentRoute: () => StudentStudentCoursesSlugRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/blog': typeof BlogRoute
  '/book': typeof BookRoute
  '/contact': typeof ContactRoute
  '/dashboard': typeof DashboardRoute
  '/events': typeof EventsRoute
  '/free-class': typeof FreeClassRoute
  '/login': typeof LoginRoute
  '/portfolio': typeof PortfolioRoute
  '/privacy': typeof PrivacyRoute
  '/programs': typeof ProgramsRoute
  '/services': typeof ServicesRoute
  '/shop': typeof ShopRoute
  '/signup': typeof SignupRoute
  '/terms': typeof TermsRoute
  '/thank-you': typeof ThankYouRoute
  '/admin': typeof AdminAdminRouteWithChildren
  '/client': typeof ClientClientRouteWithChildren
  '/student': typeof StudentStudentRouteWithChildren
  '/admin/login': typeof AdminLoginRoute
  '/admin/signup': typeof AdminSignupRoute
  '/courses/$slug': typeof CoursesSlugRoute
  '/courses/': typeof CoursesIndexRoute
  '/admin/bookings': typeof AdminAdminBookingsRoute
  '/admin/clients': typeof AdminAdminClientsRoute
  '/admin/cms': typeof AdminAdminCmsRoute
  '/admin/community': typeof AdminAdminCommunityRoute
  '/admin/courses': typeof AdminAdminCoursesRouteWithChildren
  '/admin/leads': typeof AdminAdminLeadsRoute
  '/admin/meetings': typeof AdminAdminMeetingsRoute
  '/admin/payments': typeof AdminAdminPaymentsRoute
  '/admin/settings': typeof AdminAdminSettingsRoute
  '/admin/students': typeof AdminAdminStudentsRoute
  '/client/meetings': typeof ClientClientMeetingsRoute
  '/client/messages': typeof ClientClientMessagesRoute
  '/client/payments': typeof ClientClientPaymentsRoute
  '/client/profile': typeof ClientClientProfileRoute
  '/client/projects': typeof ClientClientProjectsRoute
  '/student/community': typeof StudentStudentCommunityRoute
  '/student/courses': typeof StudentStudentCoursesRouteWithChildren
  '/student/profile': typeof StudentStudentProfileRoute
  '/student/progress': typeof StudentStudentProgressRoute
  '/student/resources': typeof StudentStudentResourcesRoute
  '/courses/$slug/checkout': typeof CoursesSlugCheckoutRoute
  '/admin/': typeof AdminAdminIndexRoute
  '/admin/courses/$courseId': typeof AdminAdminCoursesCourseIdRoute
  '/student/courses/$slug': typeof StudentStudentCoursesSlugRouteWithChildren
  '/student/courses/$slug/$lessonId': typeof StudentStudentCoursesSlugLessonIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/blog': typeof BlogRoute
  '/book': typeof BookRoute
  '/contact': typeof ContactRoute
  '/dashboard': typeof DashboardRoute
  '/events': typeof EventsRoute
  '/free-class': typeof FreeClassRoute
  '/login': typeof LoginRoute
  '/portfolio': typeof PortfolioRoute
  '/privacy': typeof PrivacyRoute
  '/programs': typeof ProgramsRoute
  '/services': typeof ServicesRoute
  '/shop': typeof ShopRoute
  '/signup': typeof SignupRoute
  '/terms': typeof TermsRoute
  '/thank-you': typeof ThankYouRoute
  '/client': typeof ClientClientRouteWithChildren
  '/student': typeof StudentStudentRouteWithChildren
  '/admin/login': typeof AdminLoginRoute
  '/admin/signup': typeof AdminSignupRoute
  '/courses/$slug': typeof CoursesSlugRoute
  '/courses': typeof CoursesIndexRoute
  '/admin/bookings': typeof AdminAdminBookingsRoute
  '/admin/clients': typeof AdminAdminClientsRoute
  '/admin/cms': typeof AdminAdminCmsRoute
  '/admin/community': typeof AdminAdminCommunityRoute
  '/admin/courses': typeof AdminAdminCoursesRouteWithChildren
  '/admin/leads': typeof AdminAdminLeadsRoute
  '/admin/meetings': typeof AdminAdminMeetingsRoute
  '/admin/payments': typeof AdminAdminPaymentsRoute
  '/admin/settings': typeof AdminAdminSettingsRoute
  '/admin/students': typeof AdminAdminStudentsRoute
  '/client/meetings': typeof ClientClientMeetingsRoute
  '/client/messages': typeof ClientClientMessagesRoute
  '/client/payments': typeof ClientClientPaymentsRoute
  '/client/profile': typeof ClientClientProfileRoute
  '/client/projects': typeof ClientClientProjectsRoute
  '/student/community': typeof StudentStudentCommunityRoute
  '/student/courses': typeof StudentStudentCoursesRouteWithChildren
  '/student/profile': typeof StudentStudentProfileRoute
  '/student/progress': typeof StudentStudentProgressRoute
  '/student/resources': typeof StudentStudentResourcesRoute
  '/courses/$slug/checkout': typeof CoursesSlugCheckoutRoute
  '/admin': typeof AdminAdminIndexRoute
  '/admin/courses/$courseId': typeof AdminAdminCoursesCourseIdRoute
  '/student/courses/$slug': typeof StudentStudentCoursesSlugRouteWithChildren
  '/student/courses/$slug/$lessonId': typeof StudentStudentCoursesSlugLessonIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_admin': typeof AdminRouteWithChildren
  '/_client': typeof ClientRouteWithChildren
  '/_student': typeof StudentRouteWithChildren
  '/about': typeof AboutRoute
  '/blog': typeof BlogRoute
  '/book': typeof BookRoute
  '/contact': typeof ContactRoute
  '/dashboard': typeof DashboardRoute
  '/events': typeof EventsRoute
  '/free-class': typeof FreeClassRoute
  '/login': typeof LoginRoute
  '/portfolio': typeof PortfolioRoute
  '/privacy': typeof PrivacyRoute
  '/programs': typeof ProgramsRoute
  '/services': typeof ServicesRoute
  '/shop': typeof ShopRoute
  '/signup': typeof SignupRoute
  '/terms': typeof TermsRoute
  '/thank-you': typeof ThankYouRoute
  '/_admin/admin': typeof AdminAdminRouteWithChildren
  '/_client/client': typeof ClientClientRouteWithChildren
  '/_student/student': typeof StudentStudentRouteWithChildren
  '/admin/login': typeof AdminLoginRoute
  '/admin/signup': typeof AdminSignupRoute
  '/courses/$slug': typeof CoursesSlugRoute
  '/courses/': typeof CoursesIndexRoute
  '/_admin/admin/bookings': typeof AdminAdminBookingsRoute
  '/_admin/admin/clients': typeof AdminAdminClientsRoute
  '/_admin/admin/cms': typeof AdminAdminCmsRoute
  '/_admin/admin/community': typeof AdminAdminCommunityRoute
  '/_admin/admin/courses': typeof AdminAdminCoursesRouteWithChildren
  '/_admin/admin/leads': typeof AdminAdminLeadsRoute
  '/_admin/admin/meetings': typeof AdminAdminMeetingsRoute
  '/_admin/admin/payments': typeof AdminAdminPaymentsRoute
  '/_admin/admin/settings': typeof AdminAdminSettingsRoute
  '/_admin/admin/students': typeof AdminAdminStudentsRoute
  '/_client/client/meetings': typeof ClientClientMeetingsRoute
  '/_client/client/messages': typeof ClientClientMessagesRoute
  '/_client/client/payments': typeof ClientClientPaymentsRoute
  '/_client/client/profile': typeof ClientClientProfileRoute
  '/_client/client/projects': typeof ClientClientProjectsRoute
  '/_student/student/community': typeof StudentStudentCommunityRoute
  '/_student/student/courses': typeof StudentStudentCoursesRouteWithChildren
  '/_student/student/profile': typeof StudentStudentProfileRoute
  '/_student/student/progress': typeof StudentStudentProgressRoute
  '/_student/student/resources': typeof StudentStudentResourcesRoute
  '/courses_/$slug/checkout': typeof CoursesSlugCheckoutRoute
  '/_admin/admin/': typeof AdminAdminIndexRoute
  '/_admin/admin/courses/$courseId': typeof AdminAdminCoursesCourseIdRoute
  '/_student/student/courses/$slug': typeof StudentStudentCoursesSlugRouteWithChildren
  '/_student/student/courses/$slug/$lessonId': typeof StudentStudentCoursesSlugLessonIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/blog'
    | '/book'
    | '/contact'
    | '/dashboard'
    | '/events'
    | '/free-class'
    | '/login'
    | '/portfolio'
    | '/privacy'
    | '/programs'
    | '/services'
    | '/shop'
    | '/signup'
    | '/terms'
    | '/thank-you'
    | '/admin'
    | '/client'
    | '/student'
    | '/admin/login'
    | '/admin/signup'
    | '/courses/$slug'
    | '/courses/'
    | '/admin/bookings'
    | '/admin/clients'
    | '/admin/cms'
    | '/admin/community'
    | '/admin/courses'
    | '/admin/leads'
    | '/admin/meetings'
    | '/admin/payments'
    | '/admin/settings'
    | '/admin/students'
    | '/client/meetings'
    | '/client/messages'
    | '/client/payments'
    | '/client/profile'
    | '/client/projects'
    | '/student/community'
    | '/student/courses'
    | '/student/profile'
    | '/student/progress'
    | '/student/resources'
    | '/courses/$slug/checkout'
    | '/admin/'
    | '/admin/courses/$courseId'
    | '/student/courses/$slug'
    | '/student/courses/$slug/$lessonId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/blog'
    | '/book'
    | '/contact'
    | '/dashboard'
    | '/events'
    | '/free-class'
    | '/login'
    | '/portfolio'
    | '/privacy'
    | '/programs'
    | '/services'
    | '/shop'
    | '/signup'
    | '/terms'
    | '/thank-you'
    | '/client'
    | '/student'
    | '/admin/login'
    | '/admin/signup'
    | '/courses/$slug'
    | '/courses'
    | '/admin/bookings'
    | '/admin/clients'
    | '/admin/cms'
    | '/admin/community'
    | '/admin/courses'
    | '/admin/leads'
    | '/admin/meetings'
    | '/admin/payments'
    | '/admin/settings'
    | '/admin/students'
    | '/client/meetings'
    | '/client/messages'
    | '/client/payments'
    | '/client/profile'
    | '/client/projects'
    | '/student/community'
    | '/student/courses'
    | '/student/profile'
    | '/student/progress'
    | '/student/resources'
    | '/courses/$slug/checkout'
    | '/admin'
    | '/admin/courses/$courseId'
    | '/student/courses/$slug'
    | '/student/courses/$slug/$lessonId'
  id:
    | '__root__'
    | '/'
    | '/_admin'
    | '/_client'
    | '/_student'
    | '/about'
    | '/blog'
    | '/book'
    | '/contact'
    | '/dashboard'
    | '/events'
    | '/free-class'
    | '/login'
    | '/portfolio'
    | '/privacy'
    | '/programs'
    | '/services'
    | '/shop'
    | '/signup'
    | '/terms'
    | '/thank-you'
    | '/_admin/admin'
    | '/_client/client'
    | '/_student/student'
    | '/admin/login'
    | '/admin/signup'
    | '/courses/$slug'
    | '/courses/'
    | '/_admin/admin/bookings'
    | '/_admin/admin/clients'
    | '/_admin/admin/cms'
    | '/_admin/admin/community'
    | '/_admin/admin/courses'
    | '/_admin/admin/leads'
    | '/_admin/admin/meetings'
    | '/_admin/admin/payments'
    | '/_admin/admin/settings'
    | '/_admin/admin/students'
    | '/_client/client/meetings'
    | '/_client/client/messages'
    | '/_client/client/payments'
    | '/_client/client/profile'
    | '/_client/client/projects'
    | '/_student/student/community'
    | '/_student/student/courses'
    | '/_student/student/profile'
    | '/_student/student/progress'
    | '/_student/student/resources'
    | '/courses_/$slug/checkout'
    | '/_admin/admin/'
    | '/_admin/admin/courses/$courseId'
    | '/_student/student/courses/$slug'
    | '/_student/student/courses/$slug/$lessonId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  ClientRoute: typeof ClientRouteWithChildren
  StudentRoute: typeof StudentRouteWithChildren
  AboutRoute: typeof AboutRoute
  BlogRoute: typeof BlogRoute
  BookRoute: typeof BookRoute
  ContactRoute: typeof ContactRoute
  DashboardRoute: typeof DashboardRoute
  EventsRoute: typeof EventsRoute
  FreeClassRoute: typeof FreeClassRoute
  LoginRoute: typeof LoginRoute
  PortfolioRoute: typeof PortfolioRoute
  PrivacyRoute: typeof PrivacyRoute
  ProgramsRoute: typeof ProgramsRoute
  ServicesRoute: typeof ServicesRoute
  ShopRoute: typeof ShopRoute
  SignupRoute: typeof SignupRoute
  TermsRoute: typeof TermsRoute
  ThankYouRoute: typeof ThankYouRoute
  AdminLoginRoute: typeof AdminLoginRoute
  AdminSignupRoute: typeof AdminSignupRoute
  CoursesSlugRoute: typeof CoursesSlugRoute
  CoursesIndexRoute: typeof CoursesIndexRoute
  CoursesSlugCheckoutRoute: typeof CoursesSlugCheckoutRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/thank-you': {
      id: '/thank-you'
      path: '/thank-you'
      fullPath: '/thank-you'
      preLoaderRoute: typeof ThankYouRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shop': {
      id: '/shop'
      path: '/shop'
      fullPath: '/shop'
      preLoaderRoute: typeof ShopRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services': {
      id: '/services'
      path: '/services'
      fullPath: '/services'
      preLoaderRoute: typeof ServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/programs': {
      id: '/programs'
      path: '/programs'
      fullPath: '/programs'
      preLoaderRoute: typeof ProgramsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portfolio': {
      id: '/portfolio'
      path: '/portfolio'
      fullPath: '/portfolio'
      preLoaderRoute: typeof PortfolioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/free-class': {
      id: '/free-class'
      path: '/free-class'
      fullPath: '/free-class'
      preLoaderRoute: typeof FreeClassRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/events': {
      id: '/events'
      path: '/events'
      fullPath: '/events'
      preLoaderRoute: typeof EventsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/book': {
      id: '/book'
      path: '/book'
      fullPath: '/book'
      preLoaderRoute: typeof BookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog': {
      id: '/blog'
      path: '/blog'
      fullPath: '/blog'
      preLoaderRoute: typeof BlogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_student': {
      id: '/_student'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof StudentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_client': {
      id: '/_client'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof ClientRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_admin': {
      id: '/_admin'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/courses/': {
      id: '/courses/'
      path: '/courses'
      fullPath: '/courses/'
      preLoaderRoute: typeof CoursesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/courses/$slug': {
      id: '/courses/$slug'
      path: '/courses/$slug'
      fullPath: '/courses/$slug'
      preLoaderRoute: typeof CoursesSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/signup': {
      id: '/admin/signup'
      path: '/admin/signup'
      fullPath: '/admin/signup'
      preLoaderRoute: typeof AdminSignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/login': {
      id: '/admin/login'
      path: '/admin/login'
      fullPath: '/admin/login'
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_student/student': {
      id: '/_student/student'
      path: '/student'
      fullPath: '/student'
      preLoaderRoute: typeof StudentStudentRouteImport
      parentRoute: typeof StudentRoute
    }
    '/_client/client': {
      id: '/_client/client'
      path: '/client'
      fullPath: '/client'
      preLoaderRoute: typeof ClientClientRouteImport
      parentRoute: typeof ClientRoute
    }
    '/_admin/admin': {
      id: '/_admin/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminAdminRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/admin/': {
      id: '/_admin/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminAdminIndexRouteImport
      parentRoute: typeof AdminAdminRoute
    }
    '/courses_/$slug/checkout': {
      id: '/courses_/$slug/checkout'
      path: '/courses/$slug/checkout'
      fullPath: '/courses/$slug/checkout'
      preLoaderRoute: typeof CoursesSlugCheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_student/student/resources': {
      id: '/_student/student/resources'
      path: '/resources'
      fullPath: '/student/resources'
      preLoaderRoute: typeof StudentStudentResourcesRouteImport
      parentRoute: typeof StudentStudentRoute
    }
    '/_student/student/progress': {
      id: '/_student/student/progress'
      path: '/progress'
      fullPath: '/student/progress'
      preLoaderRoute: typeof StudentStudentProgressRouteImport
      parentRoute: typeof StudentStudentRoute
    }
    '/_student/student/profile': {
      id: '/_student/student/profile'
      path: '/profile'
      fullPath: '/student/profile'
      preLoaderRoute: typeof StudentStudentProfileRouteImport
      parentRoute: typeof StudentStudentRoute
    }
    '/_student/student/courses': {
      id: '/_student/student/courses'
      path: '/courses'
      fullPath: '/student/courses'
      preLoaderRoute: typeof StudentStudentCoursesRouteImport
      parentRoute: typeof StudentStudentRoute
    }
    '/_student/student/community': {
      id: '/_student/student/community'
      path: '/community'
      fullPath: '/student/community'
      preLoaderRoute: typeof StudentStudentCommunityRouteImport
      parentRoute: typeof StudentStudentRoute
    }
    '/_client/client/projects': {
      id: '/_client/client/projects'
      path: '/projects'
      fullPath: '/client/projects'
      preLoaderRoute: typeof ClientClientProjectsRouteImport
      parentRoute: typeof ClientClientRoute
    }
    '/_client/client/profile': {
      id: '/_client/client/profile'
      path: '/profile'
      fullPath: '/client/profile'
      preLoaderRoute: typeof ClientClientProfileRouteImport
      parentRoute: typeof ClientClientRoute
    }
    '/_client/client/payments': {
      id: '/_client/client/payments'
      path: '/payments'
      fullPath: '/client/payments'
      preLoaderRoute: typeof ClientClientPaymentsRouteImport
      parentRoute: typeof ClientClientRoute
    }
    '/_client/client/messages': {
      id: '/_client/client/messages'
      path: '/messages'
      fullPath: '/client/messages'
      preLoaderRoute: typeof ClientClientMessagesRouteImport
      parentRoute: typeof ClientClientRoute
    }
    '/_client/client/meetings': {
      id: '/_client/client/meetings'
      path: '/meetings'
      fullPath: '/client/meetings'
      preLoaderRoute: typeof ClientClientMeetingsRouteImport
      parentRoute: typeof ClientClientRoute
    }
    '/_admin/admin/students': {
      id: '/_admin/admin/students'
      path: '/students'
      fullPath: '/admin/students'
      preLoaderRoute: typeof AdminAdminStudentsRouteImport
      parentRoute: typeof AdminAdminRoute
    }
    '/_admin/admin/settings': {
      id: '/_admin/admin/settings'
      path: '/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AdminAdminSettingsRouteImport
      parentRoute: typeof AdminAdminRoute
    }
    '/_admin/admin/payments': {
      id: '/_admin/admin/payments'
      path: '/payments'
      fullPath: '/admin/payments'
      preLoaderRoute: typeof AdminAdminPaymentsRouteImport
      parentRoute: typeof AdminAdminRoute
    }
    '/_admin/admin/meetings': {
      id: '/_admin/admin/meetings'
      path: '/meetings'
      fullPath: '/admin/meetings'
      preLoaderRoute: typeof AdminAdminMeetingsRouteImport
      parentRoute: typeof AdminAdminRoute
    }
    '/_admin/admin/leads': {
      id: '/_admin/admin/leads'
      path: '/leads'
      fullPath: '/admin/leads'
      preLoaderRoute: typeof AdminAdminLeadsRouteImport
      parentRoute: typeof AdminAdminRoute
    }
    '/_admin/admin/courses': {
      id: '/_admin/admin/courses'
      path: '/courses'
      fullPath: '/admin/courses'
      preLoaderRoute: typeof AdminAdminCoursesRouteImport
      parentRoute: typeof AdminAdminRoute
    }
    '/_admin/admin/community': {
      id: '/_admin/admin/community'
      path: '/community'
      fullPath: '/admin/community'
      preLoaderRoute: typeof AdminAdminCommunityRouteImport
      parentRoute: typeof AdminAdminRoute
    }
    '/_admin/admin/cms': {
      id: '/_admin/admin/cms'
      path: '/cms'
      fullPath: '/admin/cms'
      preLoaderRoute: typeof AdminAdminCmsRouteImport
      parentRoute: typeof AdminAdminRoute
    }
    '/_admin/admin/clients': {
      id: '/_admin/admin/clients'
      path: '/clients'
      fullPath: '/admin/clients'
      preLoaderRoute: typeof AdminAdminClientsRouteImport
      parentRoute: typeof AdminAdminRoute
    }
    '/_admin/admin/bookings': {
      id: '/_admin/admin/bookings'
      path: '/bookings'
      fullPath: '/admin/bookings'
      preLoaderRoute: typeof AdminAdminBookingsRouteImport
      parentRoute: typeof AdminAdminRoute
    }
    '/_student/student/courses/$slug': {
      id: '/_student/student/courses/$slug'
      path: '/$slug'
      fullPath: '/student/courses/$slug'
      preLoaderRoute: typeof StudentStudentCoursesSlugRouteImport
      parentRoute: typeof StudentStudentCoursesRoute
    }
    '/_admin/admin/courses/$courseId': {
      id: '/_admin/admin/courses/$courseId'
      path: '/$courseId'
      fullPath: '/admin/courses/$courseId'
      preLoaderRoute: typeof AdminAdminCoursesCourseIdRouteImport
      parentRoute: typeof AdminAdminCoursesRoute
    }
    '/_student/student/courses/$slug/$lessonId': {
      id: '/_student/student/courses/$slug/$lessonId'
      path: '/$lessonId'
      fullPath: '/student/courses/$slug/$lessonId'
      preLoaderRoute: typeof StudentStudentCoursesSlugLessonIdRouteImport
      parentRoute: typeof StudentStudentCoursesSlugRoute
    }
  }
}

interface AdminAdminCoursesRouteChildren {
  AdminAdminCoursesCourseIdRoute: typeof AdminAdminCoursesCourseIdRoute
}

const AdminAdminCoursesRouteChildren: AdminAdminCoursesRouteChildren = {
  AdminAdminCoursesCourseIdRoute: AdminAdminCoursesCourseIdRoute,
}

const AdminAdminCoursesRouteWithChildren =
  AdminAdminCoursesRoute._addFileChildren(AdminAdminCoursesRouteChildren)

interface AdminAdminRouteChildren {
  AdminAdminBookingsRoute: typeof AdminAdminBookingsRoute
  AdminAdminClientsRoute: typeof AdminAdminClientsRoute
  AdminAdminCmsRoute: typeof AdminAdminCmsRoute
  AdminAdminCommunityRoute: typeof AdminAdminCommunityRoute
  AdminAdminCoursesRoute: typeof AdminAdminCoursesRouteWithChildren
  AdminAdminLeadsRoute: typeof AdminAdminLeadsRoute
  AdminAdminMeetingsRoute: typeof AdminAdminMeetingsRoute
  AdminAdminPaymentsRoute: typeof AdminAdminPaymentsRoute
  AdminAdminSettingsRoute: typeof AdminAdminSettingsRoute
  AdminAdminStudentsRoute: typeof AdminAdminStudentsRoute
  AdminAdminIndexRoute: typeof AdminAdminIndexRoute
}

const AdminAdminRouteChildren: AdminAdminRouteChildren = {
  AdminAdminBookingsRoute: AdminAdminBookingsRoute,
  AdminAdminClientsRoute: AdminAdminClientsRoute,
  AdminAdminCmsRoute: AdminAdminCmsRoute,
  AdminAdminCommunityRoute: AdminAdminCommunityRoute,
  AdminAdminCoursesRoute: AdminAdminCoursesRouteWithChildren,
  AdminAdminLeadsRoute: AdminAdminLeadsRoute,
  AdminAdminMeetingsRoute: AdminAdminMeetingsRoute,
  AdminAdminPaymentsRoute: AdminAdminPaymentsRoute,
  AdminAdminSettingsRoute: AdminAdminSettingsRoute,
  AdminAdminStudentsRoute: AdminAdminStudentsRoute,
  AdminAdminIndexRoute: AdminAdminIndexRoute,
}

const AdminAdminRouteWithChildren = AdminAdminRoute._addFileChildren(
  AdminAdminRouteChildren,
)

interface AdminRouteChildren {
  AdminAdminRoute: typeof AdminAdminRouteWithChildren
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminAdminRoute: AdminAdminRouteWithChildren,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface ClientClientRouteChildren {
  ClientClientMeetingsRoute: typeof ClientClientMeetingsRoute
  ClientClientMessagesRoute: typeof ClientClientMessagesRoute
  ClientClientPaymentsRoute: typeof ClientClientPaymentsRoute
  ClientClientProfileRoute: typeof ClientClientProfileRoute
  ClientClientProjectsRoute: typeof ClientClientProjectsRoute
}

const ClientClientRouteChildren: ClientClientRouteChildren = {
  ClientClientMeetingsRoute: ClientClientMeetingsRoute,
  ClientClientMessagesRoute: ClientClientMessagesRoute,
  ClientClientPaymentsRoute: ClientClientPaymentsRoute,
  ClientClientProfileRoute: ClientClientProfileRoute,
  ClientClientProjectsRoute: ClientClientProjectsRoute,
}

const ClientClientRouteWithChildren = ClientClientRoute._addFileChildren(
  ClientClientRouteChildren,
)

interface ClientRouteChildren {
  ClientClientRoute: typeof ClientClientRouteWithChildren
}

const ClientRouteChildren: ClientRouteChildren = {
  ClientClientRoute: ClientClientRouteWithChildren,
}

const ClientRouteWithChildren =
  ClientRoute._addFileChildren(ClientRouteChildren)

interface StudentStudentCoursesSlugRouteChildren {
  StudentStudentCoursesSlugLessonIdRoute: typeof StudentStudentCoursesSlugLessonIdRoute
}

const StudentStudentCoursesSlugRouteChildren: StudentStudentCoursesSlugRouteChildren =
  {
    StudentStudentCoursesSlugLessonIdRoute:
      StudentStudentCoursesSlugLessonIdRoute,
  }

const StudentStudentCoursesSlugRouteWithChildren =
  StudentStudentCoursesSlugRoute._addFileChildren(
    StudentStudentCoursesSlugRouteChildren,
  )

interface StudentStudentCoursesRouteChildren {
  StudentStudentCoursesSlugRoute: typeof StudentStudentCoursesSlugRouteWithChildren
}

const StudentStudentCoursesRouteChildren: StudentStudentCoursesRouteChildren = {
  StudentStudentCoursesSlugRoute: StudentStudentCoursesSlugRouteWithChildren,
}

const StudentStudentCoursesRouteWithChildren =
  StudentStudentCoursesRoute._addFileChildren(
    StudentStudentCoursesRouteChildren,
  )

interface StudentStudentRouteChildren {
  StudentStudentCommunityRoute: typeof StudentStudentCommunityRoute
  StudentStudentCoursesRoute: typeof StudentStudentCoursesRouteWithChildren
  StudentStudentProfileRoute: typeof StudentStudentProfileRoute
  StudentStudentProgressRoute: typeof StudentStudentProgressRoute
  StudentStudentResourcesRoute: typeof StudentStudentResourcesRoute
}

const StudentStudentRouteChildren: StudentStudentRouteChildren = {
  StudentStudentCommunityRoute: StudentStudentCommunityRoute,
  StudentStudentCoursesRoute: StudentStudentCoursesRouteWithChildren,
  StudentStudentProfileRoute: StudentStudentProfileRoute,
  StudentStudentProgressRoute: StudentStudentProgressRoute,
  StudentStudentResourcesRoute: StudentStudentResourcesRoute,
}

const StudentStudentRouteWithChildren = StudentStudentRoute._addFileChildren(
  StudentStudentRouteChildren,
)

interface StudentRouteChildren {
  StudentStudentRoute: typeof StudentStudentRouteWithChildren
}

const StudentRouteChildren: StudentRouteChildren = {
  StudentStudentRoute: StudentStudentRouteWithChildren,
}

const StudentRouteWithChildren =
  StudentRoute._addFileChildren(StudentRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  ClientRoute: ClientRouteWithChildren,
  StudentRoute: StudentRouteWithChildren,
  AboutRoute: AboutRoute,
  BlogRoute: BlogRoute,
  BookRoute: BookRoute,
  ContactRoute: ContactRoute,
  DashboardRoute: DashboardRoute,
  EventsRoute: EventsRoute,
  FreeClassRoute: FreeClassRoute,
  LoginRoute: LoginRoute,
  PortfolioRoute: PortfolioRoute,
  PrivacyRoute: PrivacyRoute,
  ProgramsRoute: ProgramsRoute,
  ServicesRoute: ServicesRoute,
  ShopRoute: ShopRoute,
  SignupRoute: SignupRoute,
  TermsRoute: TermsRoute,
  ThankYouRoute: ThankYouRoute,
  AdminLoginRoute: AdminLoginRoute,
  AdminSignupRoute: AdminSignupRoute,
  CoursesSlugRoute: CoursesSlugRoute,
  CoursesIndexRoute: CoursesIndexRoute,
  CoursesSlugCheckoutRoute: CoursesSlugCheckoutRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
